development:
  domain: <%= ENV["AUTH0_DOMAIN"] %>
  audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>

test:
  domain: <%= ENV["AUTH0_DOMAIN"] %>
  audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>

production:
  domain: <%= ENV["AUTH0_DOMAIN"] %>
  audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>